import React from 'react';
export const analysisDetails = () => <div>analysis distinct</div>;
export const analysis_detail_0 = (p:any)=> <div>analysis 0 results</div>;
export const analysis_detail_1 = (p:any)=> <div>analysis 1 significance</div>;
export const analysis_detail_2 = (p:any)=> <div>analysis 2 interpretation</div>;
export const analysis_detail_3 = (p:any)=> <div>analysis 3 plain language</div>;
export const analysis_detail_4 = (p:any)=> <div>analysis 4 results</div>;
export const analysis_detail_5 = (p:any)=> <div>analysis 5 significance</div>;
export const analysis_detail_6 = (p:any)=> <div>analysis 6 interpretation</div>;
export const analysis_detail_7 = (p:any)=> <div>analysis 7 plain language</div>;
export const analysis_detail_8 = (p:any)=> <div>analysis 8 results</div>;
export const analysis_detail_9 = (p:any)=> <div>analysis 9 significance</div>;
export const analysis_detail_10 = (p:any)=> <div>analysis 10 interpretation</div>;
export const analysis_detail_11 = (p:any)=> <div>analysis 11 plain language</div>;
export const analysis_detail_12 = (p:any)=> <div>analysis 12 results</div>;
export const analysis_detail_13 = (p:any)=> <div>analysis 13 significance</div>;
export const analysis_detail_14 = (p:any)=> <div>analysis 14 interpretation</div>;
export const analysis_detail_15 = (p:any)=> <div>analysis 15 plain language</div>;
export const analysis_detail_16 = (p:any)=> <div>analysis 16 results</div>;
export const analysis_detail_17 = (p:any)=> <div>analysis 17 significance</div>;
export const analysis_detail_18 = (p:any)=> <div>analysis 18 interpretation</div>;
export const analysis_detail_19 = (p:any)=> <div>analysis 19 plain language</div>;